packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/common'
  - 'packages/main/*'
  - 'packages/preload'
  - 'packages/render'
  - 'packages/share'
  - 'buildin/*'
  - 'tsconfig'
  # exclude packages that are inside test directories
  - '!**/test/**'
