packages:
  # all packages in subdirs of packages/ and components/
  - 'packages-common/*'
  - 'packages-main/main'
  - 'packages-main/m-*/*'
  - 'packages-main/p-*/*'
  - 'packages-preload/preload'
  - 'packages-preload/m-*/*'
  - 'packages-preload/p-*/*'
  - 'packages-render/render'
  - 'packages-render/m-*/*'
  - 'packages-render/p-*/*'
  - 'packages-render/muya'
  - 'buildin/*'
  - 'config'
  # exclude packages that are inside test directories
  - '!**/test/**'
