packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/common'
  - 'packages/main'
  - 'packages/main-packages/*'
  - 'packages/preload'
  - 'packages/preload-packages/*'
  - 'packages/render'
  - 'packages/render-packages/*'
  - 'buildin/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
