packages:
  # all packages in subdirs of packages/ and components/
  - 'packages-common/common'
  - 'packages-common/m-*/*'
  - 'packages-main/main'
  - 'packages-main/m-*/*'
  - 'packages-preload/preload'
  - 'packages-preload/m-*/*'
  - 'packages-render/render'
  - 'packages-render/m-*/*'
  - 'buildin/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
